services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - "8084:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - yii-network

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - yii-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      PMA_USER: 
      PMA_PASSWORD: 
      UPLOAD_LIMIT: 100M
    depends_on:
      - db
    networks:
      - yii-network

networks:
  yii-network:

volumes:
  db-data: